import type { Stage, PipelineContext, StageOutput } from "./types.js";
import { spawnSafe } from "../../utils/process.js";
import { readTicketContext } from "../../memory/context-builder.js";

export const gitStage: Stage = {
  id: "git",
  name: "Git & PR",
  model: "haiku",

  async run(ctx: PipelineContext): Promise<StageOutput> {
    const { config, ticketKey, state } = ctx;
    const branchName = state.current.branchName;
    if (!branchName)
      throw new Error("No branch name in state — code stage must run first");

    const workdir = config.workspace.rootDir;
    const ticketCtx = readTicketContext(ctx.memoryDir);
    const summaryLine = ticketCtx
      .split("\n")
      .find((l) => l.startsWith("## Summary"));
    const summary =
      ticketCtx.split("\n")[
        ticketCtx.split("\n").indexOf(summaryLine ?? "") + 1
      ] ?? ticketKey;

    ctx.logger.info(
      { ticketKey, branchName },
      "Pushing branch and creating PR",
    );

    if (!ctx.dryRun) {
      // Push branch
      await spawnSafe("git", ["push", "origin", branchName], { cwd: workdir });

      // Create PR via GitHub client
      const prNumber = await ctx.github.createPR({
        title: `[${ticketKey}] ${summary.trim()}`,
        body: buildPrBody(ticketKey, ticketCtx),
        head: branchName,
        base: config.github.defaultBranch ?? "main",
        draft: config.github.prDraftByDefault ?? false,
      });

      if (config.github.reviewers?.length) {
        await ctx.github.addReviewers(prNumber, config.github.reviewers);
      }

      ctx.logger.info({ ticketKey, prNumber }, "PR created");
      return { branchName, prNumber };
    }

    return { branchName, prNumber: null };
  },
};

function buildPrBody(ticketKey: string, ticketCtx: string): string {
  return `## ${ticketKey}

${ticketCtx}

---
*Generated by jiraACP automated pipeline*`;
}
